server:
  servlet:
    port: 8080
    contextPath: /api

spring:
  application:
    name: Quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: joy@123

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect